# coding=utf-8

from __future__ import unicode_literals
from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats = (
        '{{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{first_name_male}} {{last_name}}',
        '{{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{last_name}}',
        '{{first_name_female}} {{last_name}}',
    )

    first_names_male = (
           'Jose',
 'Daniel',
 'Diego',
 'Carlos',
 'Juan',
 'Juan Carlos',
 'Gabriel',
 'Michael',
 'Jesús',
 'Henry',
 'Andre',
 'Miguel',
 'H.',
 'Isac',
 'Victor',
 'Julio',
 'Richard',
 'Alexander',
 'Christian',
 'Jefry',
 'Piero',
 'Aaron',
 'Danny',
 'Luis',
 'Pedro',
 'A.',
 'Angel',
 'Alex',
 'Elmer',
 'Ricardo',
 'Colbert',
 'Cristopher Quispe',
 'Alois',
 'Percy',
 'Clegauth',
 'Eduardo',
 'William',
 'Mariano',
 'Ric',
 'Ozcar',
 'Yonatan',
 'Danii',
 'Roger',
 'Krloz',
 'Sebastian',
 'Patrick',
 'Hugo',
 'Andrew',
 'Jean Pier Ortega',
 'Farik',
 'Joaquin',
 'Jude',
 'Aldo',
 'Juli0',
 'Willian',
 'Bruce',
 'Luyis',
 'Luis Espinoza',
 'M.',
 'Renán',
 'Jorge Luis',
 'Darwin',
 'Rodrigo',
 'Ventanilla',


    )

    first_names_female = (
            'Andrea', 'Sandra', 'Daniela', 'Maria', 'Veronica', 'Alessandra', 'Cristina', 'Gabriela', 'Jhady', 'Karen', 'Liz', 'Carito', 'Melisa', 'Nicolle', 'Mayra', 'Sofia', 'Naida', 'Gina', 'Maricielo', 'Fiorella', 'Nicole', 'Luz', 'Yessica', 'Gaby', 'Lesli', 'Vanessa', 'Melissa', 'Sara', 'Abigail', 'Silvia Katheryn', 'Serena', 'Perla', 'Esmeralda', 'Jacky', 'Vallya Corali', 'Angie Rojas', 'Briggyd', 'Estefani', 'Cybel', 'Megaly', 'Meylin.Wan', 'Alisson', 'Miluska', 'Lizzie', 'Lilian Carolina', 'Val', 'Leslie', 'Valery Garayar', 'Milagros', 'Grecia', 'Lisette', 'Hernan', 'Lililiana', 'Ayme', 'Geral', 'Luna', 'Erika', 'Valeria', 'Katy', 'Ingrid', 'Amarilis', 'Darly', 'Arely', 'Liliana',



    )

    first_names = first_names_male + first_names_female

    last_names = (
          'Rodríguez', 'González', 'Hernández', 'García', 'Martínez', 'López', 'Sánchez', 'Pérez', ' Gómez ', 'Amaru', 'Conde', 'Condor', 'Cusi', 'Huamani', 'Huanca', 'Nina', 'Ñahui', 'Vilca ', 'Apaza', 'Arpasi', 'Cahuana', 'Choque', 'Mamani', 'Quispe ', 'Ihuaraqui', 'Manihuari', 'Mozombite', 'Tuanama', 'Alvarez', 'Fernandez', 'Garcia', 'Chávez', 'Díaz', 'Gonzales', 'Wachalla', 'Wallpa', 'Wampu', 'Wanapako', 'Wanapaqu', 'Wanca', 'Wanka', 'Wankilla', 'Wankiri', 'Villca', 'Ticuna', 'Ticunipa', 'Tikuna', 'Tikunipa', 'Tintaya', 'W.', 'G.', 'M.', 'D.', 'A.', 'T.', 'Titu', 'Tola', 'Pacohuanca', 'Pacosillo', 'Pacsi', 'Pacsipati', 'Paillo', 'Pakari', 'Pako',



    )

    prefixes_male = (

    )
    prefixes_female = (

    )

    suffixes = ()
